DROP TABLE PRODUCT;

CREATE TABLE PRODUCT (
    product_id VARCHAR2(20) CONSTRAINT PK_PRODUCTID PRIMARY KEY,
    p_name VARCHAR2(20) NOT NULL,
    price VARCHAR2(20) NOT NULL,
    description VARCHAR2(50)
);

COMMENT ON COLUMN PRODUCT.product_id IS '상품ID';
COMMENT ON COLUMN PRODUCT.p_name IS '상품이름';
COMMENT ON COLUMN PRODUCT.price IS '상품ID';
COMMENT ON COLUMN PRODUCT.description IS '상품정보';

TRUNCATE TABLE PRODUCT;

INSERT INTO PRODUCT VALUES('nb_ss7', '삼성노트북', 1570000, '시리즈7');
INSERT INTO PRODUCT VALUES('nb_ama4', '맥북에어', 1200000, 'xcode4');
INSERT INTO PRODUCT VALUES('pc_ibm', 'ibmPC', 750000, 'window8');

SELECT * FROM PRODUCT;

COMMIT;
